---
captiveportal_virtualenv_dir: "/usr/local/connectbox/captive_portal_venv"
captiveportal_run_directory: "/run/captiveportal"
captiveportal_pid_file: "{{ captiveportal_run_directory }}/pid"
captiveportal_listen_port: 5001
captiveportal_user: _connectbox
captiveportal_group: _connectbox
captiveportal_log_level: "error"
