---

# Note: OS specific variables are included in the order of the hierarchy of their fork:
#
# Debian─┬─Ubuntu───Armbian
#        ├─Raspbian
#        └─Armbian
#
# (See also https://github.com/ConnectBox/connectbox-pi/wiki/Differentiating-platform-by-ansible-variables)

- hosts: all
  pre_tasks:
    - name: Include OS family variables
      include_vars: "group_vars/{{ ansible_os_family|lower }}"
    - name: Include Distribution variables
      include_vars: "group_vars/{{ ansible_distribution|lower }}"
    - name: Include Target specific variables
      include_vars: "group_vars/{{ ansible_lsb['id']|lower }}"
    - name: Check for Armbian info
      stat:
        path: "/etc/armbian.txt"
      register: armbian_file
    - name: Check for Armbian Release
      stat:
        path: "/etc/armbian-release"
      register: armbian_release_file
    - name: Include Armbian specific variables
      include_vars: "group_vars/armbian"
      when: armbian_file.stat.exists == True or armbian_release_file.stat.exists == True
    # This is probably better implemented as an ansible plugin so we can support
    #  machines with 3.x series kernels (armbian legacy)
    # We will get errors when this file doesn't exist (3.x series kernels) so we
    #  ignore errors. It's ok if this is unset because we're only looking for a
    #  string inside the registered result.
    - name: Register machine type
      command: cat /sys/firmware/devicetree/base/model
      register: machine_type
      ignore_errors: yes
      changed_when: False
  become: yes
  roles:
    - connectbox-pi
    - { role: image-preparation, when: do_image_preparation }
