---
# dns-dhcp needs to come last, given it adjusts resolv.conf and breaks
#  subsequent lookups
dependencies:
  - bootstrap
  - wifi-ap
  - geerlingguy.nginx
  - mikegleasonjr.firewall
  - usb-content
  - dns-dhcp
